import '../../core/models/food_item.dart';

/// Static food database with lipid-impact metadata.
///
/// Featured foods have rich metadata; remaining foods carry sensible defaults
/// so the UI never crashes on a missing entry.
class FoodDatabase {
  FoodDatabase._();

  // ── Featured foods with full metadata ─────────────────────────────────────

  static const List<FoodItem> featured = [
    // ── Best Choices ─────────────────────────────────────────────────────
    FoodItem(
      name: 'Salmon',
      category: FoodCategory.good,
      impactScore: 2.3,
      impactLabel: 'Reduces triglycerides significantly',
      mechanismNote: 'Rich in EPA & DHA omega-3 fatty acids',
      details: [
        'Lowers triglycerides by 20–30% with regular intake',
        'Raises HDL (good cholesterol)',
        'Reduces arterial inflammation',
        'Supports healthy blood pressure',
      ],
      helpsLdl: false,
      helpsTriglycerides: true,
    ),
    FoodItem(
      name: 'Oats',
      category: FoodCategory.good,
      impactScore: 2.1,
      impactLabel: 'Supports LDL reduction',
      mechanismNote: 'High in beta-glucan soluble fiber',
      details: [
        'Beta-glucan binds LDL in the gut and removes it',
        'FDA-approved heart-health claim',
        '3g beta-glucan/day can lower LDL by 5–10%',
        'Also stabilises blood sugar',
      ],
      helpsLdl: true,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Walnuts',
      category: FoodCategory.good,
      impactScore: 1.9,
      impactLabel: 'Lowers LDL & triglycerides',
      mechanismNote: 'Omega-3 ALA + polyunsaturated fats',
      details: [
        'Reduces LDL by ~10% with 1.5 oz/day',
        'Lowers triglycerides',
        'Improves total/HDL ratio',
        'Rich in antioxidant polyphenols',
      ],
      helpsLdl: true,
      helpsTriglycerides: true,
    ),
    FoodItem(
      name: 'Almonds',
      category: FoodCategory.good,
      impactScore: 1.8,
      impactLabel: 'Supports LDL reduction',
      mechanismNote: 'Monounsaturated fats + vitamin E',
      details: [
        'Lowers LDL by 5–10% with 1.5 oz/day',
        'Does not reduce HDL',
        'Reduces post-meal blood sugar spikes',
        'High in magnesium for blood pressure',
      ],
      helpsLdl: true,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Flax Seeds',
      category: FoodCategory.good,
      impactScore: 1.7,
      impactLabel: 'Lowers LDL & triglycerides',
      mechanismNote: 'Soluble fiber + ALA omega-3',
      details: [
        'Ground flax lowers LDL by ~7%',
        'Reduces triglycerides',
        'Lignans support overall cardiovascular health',
        'Use ground, not whole, for absorption',
      ],
      helpsLdl: true,
      helpsTriglycerides: true,
    ),
    FoodItem(
      name: 'Lentils',
      category: FoodCategory.good,
      impactScore: 1.6,
      impactLabel: 'Supports LDL reduction',
      mechanismNote: 'Soluble fiber + plant protein',
      details: [
        'Soluble fiber traps bile acids, lowering LDL',
        'Plant protein replaces saturated-fat sources',
        'High in folate for heart health',
        'Low glycemic index',
      ],
      helpsLdl: true,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Avocado',
      category: FoodCategory.good,
      impactScore: 1.5,
      impactLabel: 'Improves cholesterol ratio',
      mechanismNote: 'Oleic acid + beta-sitosterol',
      details: [
        'Reduces LDL and total cholesterol',
        'Raises HDL (the good kind)',
        'Plant sterols block cholesterol absorption',
        'Replaces saturated fats in the diet',
      ],
      helpsLdl: true,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Sardines',
      category: FoodCategory.good,
      impactScore: 2.1,
      impactLabel: 'Reduces triglycerides significantly',
      mechanismNote: 'Concentrated EPA & DHA omega-3',
      details: [
        'Lowers triglycerides by up to 30%',
        'One of the richest omega-3 sources available',
        'Raises HDL',
        'Low in mercury compared to larger fish',
      ],
      helpsLdl: false,
      helpsTriglycerides: true,
    ),
    FoodItem(
      name: 'Chia Seeds',
      category: FoodCategory.good,
      impactScore: 1.4,
      impactLabel: 'Lowers LDL & triglycerides',
      mechanismNote: 'Soluble fiber + ALA omega-3',
      details: [
        'Forms a gel that traps cholesterol in the gut',
        'Reduces triglycerides with regular intake',
        'High fiber supports healthy gut microbiome',
        'Easy to add to any meal',
      ],
      helpsLdl: true,
      helpsTriglycerides: true,
    ),
    FoodItem(
      name: 'Chickpeas',
      category: FoodCategory.good,
      impactScore: 1.3,
      impactLabel: 'Supports LDL reduction',
      mechanismNote: 'Soluble fiber + plant sterols',
      details: [
        'Regular legume intake linked to 5% lower LDL',
        'Plant sterols reduce cholesterol absorption',
        'High protein keeps you full, reducing fatty snacks',
        'Low glycemic index',
      ],
      helpsLdl: true,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Tofu',
      category: FoodCategory.good,
      impactScore: 1.2,
      impactLabel: 'Supports LDL reduction',
      mechanismNote: 'Soy isoflavones + low saturated fat',
      details: [
        '25g soy protein/day can lower LDL by 5–6%',
        'Replaces high saturated fat animal proteins',
        'Isoflavones have mild antioxidant effects',
        'Good source of complete plant protein',
      ],
      helpsLdl: true,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Blueberries',
      category: FoodCategory.good,
      impactScore: 1.0,
      impactLabel: 'Supports heart health',
      mechanismNote: 'Anthocyanins reduce oxidised LDL',
      details: [
        'Antioxidants prevent LDL from becoming harmful',
        'Reduces arterial stiffness',
        'Anti-inflammatory effect on blood vessels',
        'High fiber with low sugar',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Quinoa',
      category: FoodCategory.good,
      impactScore: 1.0,
      impactLabel: 'Supports cholesterol profile',
      mechanismNote: 'Saponins + plant sterols',
      details: [
        'Contains cholesterol-blocking plant sterols',
        'High fiber improves overall lipid profile',
        'Complete protein avoids need for fatty meats',
        'Low glycemic index',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Apples',
      category: FoodCategory.good,
      impactScore: 0.8,
      impactLabel: 'Mild LDL support',
      mechanismNote: 'Pectin soluble fiber',
      details: [
        'Pectin binds LDL and removes it via digestion',
        'Polyphenols reduce LDL oxidation',
        'Low calorie, high fiber snack',
        'Keeps you full, reducing less healthy choices',
      ],
      helpsLdl: true,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Spinach',
      category: FoodCategory.good,
      impactScore: 0.7,
      impactLabel: 'Supports heart health',
      mechanismNote: 'Lutein + folate reduce arterial inflammation',
      details: [
        'Lutein prevents cholesterol sticking to artery walls',
        'Folate lowers homocysteine, a cardiovascular risk marker',
        'Very low calorie, high nutrient density',
        'Versatile in salads, smoothies, and cooked dishes',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Chicken Breast',
      category: FoodCategory.good,
      impactScore: 0.6,
      impactLabel: 'Heart-healthy protein',
      mechanismNote: 'Low saturated fat, high lean protein',
      details: [
        'Replacing red meat with chicken lowers LDL',
        'Low saturated fat keeps behavior score intact',
        'Supports lean muscle without lipid impact',
        'Best baked, grilled, or poached — not fried',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),

    // ── Limit Foods ───────────────────────────────────────────────────────
    FoodItem(
      name: 'Eggs (Whole)',
      category: FoodCategory.limit,
      impactScore: -0.3,
      impactLabel: 'Moderate dietary cholesterol',
      mechanismNote: 'High choline; cholesterol impact varies by person',
      details: [
        '1–2 eggs/day is well-tolerated by most people',
        'Dietary cholesterol has less impact than saturated fat',
        'Some individuals are "hyper-responders" — monitor your labs',
        'Egg whites have zero cholesterol impact',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Chocolate (Dark 70%+)',
      category: FoodCategory.limit,
      impactScore: -0.2,
      impactLabel: 'Moderate — portion matters',
      mechanismNote: 'Flavonoids offset some saturated fat',
      details: [
        'Flavonoids may modestly improve HDL',
        'Still contains saturated fat — keep to 1 oz',
        'Higher cacao % = fewer added sugars',
        'Milk chocolate has much higher negative impact',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Shrimp',
      category: FoodCategory.limit,
      impactScore: -0.4,
      impactLabel: 'Higher dietary cholesterol',
      mechanismNote: 'Low saturated fat but significant cholesterol',
      details: [
        'High in dietary cholesterol but low in saturated fat',
        'Net effect on blood cholesterol is usually mild',
        'Fine in moderation (3–4 oz, a few times/week)',
        'Avoid if prescribed strict low-cholesterol diet',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Beef (Lean Cuts)',
      category: FoodCategory.limit,
      impactScore: -0.8,
      impactLabel: 'Raises LDL at higher quantities',
      mechanismNote: 'Saturated fat content raises LDL',
      details: [
        'Lean cuts (sirloin, tenderloin) have less impact',
        'Keep to 3–4 oz, 2–3 times per week',
        'Grass-fed beef has slightly better fat profile',
        'Pair with vegetables to offset impact',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Alcohol (Wine)',
      category: FoodCategory.limit,
      impactScore: -0.5,
      impactLabel: 'Raises triglycerides in excess',
      mechanismNote: 'The liver converts alcohol to triglycerides',
      details: [
        '1 drink/day may modestly raise HDL',
        '2+ drinks raises triglycerides meaningfully',
        'No health organization recommends starting to drink',
        'Alcohol also affects medication efficacy',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),

    // ── Avoid Foods ───────────────────────────────────────────────────────
    FoodItem(
      name: 'Bacon',
      category: FoodCategory.avoid,
      impactScore: -2.8,
      impactLabel: 'Significantly raises LDL',
      mechanismNote: 'Very high saturated fat + sodium',
      details: [
        'One of the highest saturated fat foods per serving',
        'Directly raises LDL cholesterol',
        'Processed meats linked to cardiovascular disease',
        'Turkey bacon is only slightly better',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Butter',
      category: FoodCategory.avoid,
      impactScore: -2.5,
      impactLabel: 'Raises LDL significantly',
      mechanismNote: '~7g saturated fat per tablespoon',
      details: [
        'Major driver of LDL increase in Western diets',
        'Replace with olive oil or avocado oil',
        'Even small daily amounts accumulate quickly',
        'Ghee has a similar profile',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Sausage',
      category: FoodCategory.avoid,
      impactScore: -2.6,
      impactLabel: 'Raises LDL significantly',
      mechanismNote: 'High saturated fat + processed meat',
      details: [
        'Combines saturated fat with processed meat risks',
        'Sodium worsens blood pressure alongside LDL',
        'Directly worsens your behavior score in this app',
        'Plant-based sausage alternatives are far better',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Fast Food',
      category: FoodCategory.avoid,
      impactScore: -3.2,
      impactLabel: 'Worst single-meal LDL impact',
      mechanismNote: 'Trans fat + saturated fat + refined carbs',
      details: [
        'Combination of trans fat, sat fat, and sugar is worst-case',
        'A single meal can spike TG for 4–6 hours',
        'Sodium raises blood pressure acutely',
        'Caloric density promotes weight gain, worsening lipids',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Deep-Fried Foods',
      category: FoodCategory.avoid,
      impactScore: -3.0,
      impactLabel: 'Raises LDL & triglycerides',
      mechanismNote: 'Trans fat formed during frying',
      details: [
        'Repeated-use frying oils generate harmful trans fats',
        'Trans fat is uniquely bad: raises LDL AND lowers HDL',
        'Directly triggers high-satfat-day flag in your score',
        'Air-frying or baking is a direct substitute',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
    FoodItem(
      name: 'Soda',
      category: FoodCategory.avoid,
      impactScore: -1.8,
      impactLabel: 'Raises triglycerides',
      mechanismNote: 'Fructose is converted to triglycerides by the liver',
      details: [
        'Added sugar directly drives triglyceride production',
        'Even "natural" fruit juices have this effect',
        'One can/day linked to 30% higher TG levels',
        'Sparkling water with fruit is a clean alternative',
      ],
      helpsLdl: false,
      helpsTriglycerides: false,
    ),
  ];

  // ── Simple entries for remaining foods ────────────────────────────────────
  // These use category-default impact values and minimal metadata.

  static const List<FoodItem> _simpleGood = [
    FoodItem(name: 'Almond Milk', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Low saturated fat', mechanismNote: 'Plant-based milk alternative'),
    FoodItem(name: 'Amaranth', category: FoodCategory.good, impactScore: 0.6, impactLabel: 'Supports cholesterol profile', mechanismNote: 'Fiber-rich whole grain'),
    FoodItem(name: 'Apricots', category: FoodCategory.good, impactScore: 0.4, impactLabel: 'Heart-healthy fruit', mechanismNote: 'Soluble fiber + antioxidants'),
    FoodItem(name: 'Artichokes', category: FoodCategory.good, impactScore: 0.8, impactLabel: 'Supports LDL reduction', mechanismNote: 'Cynarin boosts bile production'),
    FoodItem(name: 'Arugula', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Heart-healthy green', mechanismNote: 'Nitrates support blood vessel health'),
    FoodItem(name: 'Asparagus', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Supports heart health', mechanismNote: 'Inulin fiber + antioxidants'),
    FoodItem(name: 'Bananas', category: FoodCategory.good, impactScore: 0.4, impactLabel: 'Heart-healthy fruit', mechanismNote: 'Pectin fiber + potassium'),
    FoodItem(name: 'Barley', category: FoodCategory.good, impactScore: 1.2, impactLabel: 'Supports LDL reduction', mechanismNote: 'Beta-glucan soluble fiber (like oats)'),
    FoodItem(name: 'Basmati Rice', category: FoodCategory.good, impactScore: 0.3, impactLabel: 'Lower glycemic than white rice', mechanismNote: 'Moderate fiber, lower GI'),
    FoodItem(name: 'Beans', category: FoodCategory.good, impactScore: 1.4, impactLabel: 'Supports LDL reduction', mechanismNote: 'High soluble fiber + plant protein'),
    FoodItem(name: 'Beets', category: FoodCategory.good, impactScore: 0.6, impactLabel: 'Supports heart health', mechanismNote: 'Betaine reduces homocysteine'),
    FoodItem(name: 'Bell Peppers', category: FoodCategory.good, impactScore: 0.4, impactLabel: 'Heart-healthy vegetable', mechanismNote: 'Vitamin C + antioxidants'),
    FoodItem(name: 'Blackberries', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Supports heart health', mechanismNote: 'Anthocyanins reduce LDL oxidation'),
    FoodItem(name: 'Bok Choy', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Heart-healthy green', mechanismNote: 'Low calorie, high nutrients'),
    FoodItem(name: 'Broccoli', category: FoodCategory.good, impactScore: 0.9, impactLabel: 'Supports heart health', mechanismNote: 'Soluble fiber + sulforaphane'),
    FoodItem(name: 'Brown Rice', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Whole grain choice', mechanismNote: 'More fiber than white rice'),
    FoodItem(name: 'Bulgur', category: FoodCategory.good, impactScore: 0.6, impactLabel: 'Supports cholesterol profile', mechanismNote: 'High fiber whole grain'),
    FoodItem(name: 'Cabbage', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Heart-healthy vegetable', mechanismNote: 'Fiber + anti-inflammatory'),
    FoodItem(name: 'Canola Oil', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Supports cholesterol profile', mechanismNote: 'Mostly monounsaturated fat'),
    FoodItem(name: 'Carrots', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Supports heart health', mechanismNote: 'Pectin fiber + beta-carotene'),
    FoodItem(name: 'Cashews', category: FoodCategory.good, impactScore: 0.8, impactLabel: 'Supports LDL reduction', mechanismNote: 'Monounsaturated fat + low sat fat'),
    FoodItem(name: 'Cauliflower', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Heart-healthy vegetable', mechanismNote: 'Fiber + sulforaphane'),
    FoodItem(name: 'Cherries', category: FoodCategory.good, impactScore: 0.6, impactLabel: 'Supports heart health', mechanismNote: 'Anthocyanins + anti-inflammatory'),
    FoodItem(name: 'Cod', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Lean heart-healthy protein', mechanismNote: 'Low fat, high lean protein'),
    FoodItem(name: 'Edamame', category: FoodCategory.good, impactScore: 1.1, impactLabel: 'Supports LDL reduction', mechanismNote: 'Soy isoflavones + fiber'),
    FoodItem(name: 'Eggplant', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Supports heart health', mechanismNote: 'Chlorogenic acid + fiber'),
    FoodItem(name: 'Grapes', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Supports heart health', mechanismNote: 'Resveratrol + polyphenols'),
    FoodItem(name: 'Guava', category: FoodCategory.good, impactScore: 0.6, impactLabel: 'Supports heart health', mechanismNote: 'Soluble fiber + vitamin C'),
    FoodItem(name: 'Haddock', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Lean heart-healthy protein', mechanismNote: 'Low saturated fat'),
    FoodItem(name: 'Halibut', category: FoodCategory.good, impactScore: 0.8, impactLabel: 'Supports heart health', mechanismNote: 'Omega-3 + lean protein'),
    FoodItem(name: 'Kale', category: FoodCategory.good, impactScore: 0.8, impactLabel: 'Supports heart health', mechanismNote: 'Fiber + bile acid binding'),
    FoodItem(name: 'Kidney Beans', category: FoodCategory.good, impactScore: 1.3, impactLabel: 'Supports LDL reduction', mechanismNote: 'Soluble fiber + plant protein'),
    FoodItem(name: 'Kiwi', category: FoodCategory.good, impactScore: 0.6, impactLabel: 'Supports heart health', mechanismNote: 'Vitamin C + fiber'),
    FoodItem(name: 'Lima Beans', category: FoodCategory.good, impactScore: 1.2, impactLabel: 'Supports LDL reduction', mechanismNote: 'Soluble fiber + plant protein'),
    FoodItem(name: 'Low-fat Milk (1%)', category: FoodCategory.good, impactScore: 0.3, impactLabel: 'Lower saturated fat than whole milk', mechanismNote: 'Calcium without excess sat fat'),
    FoodItem(name: 'Mango', category: FoodCategory.good, impactScore: 0.4, impactLabel: 'Heart-healthy fruit', mechanismNote: 'Fiber + antioxidants'),
    FoodItem(name: 'Millet', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Whole grain choice', mechanismNote: 'Magnesium + fiber'),
    FoodItem(name: 'Oat Bran', category: FoodCategory.good, impactScore: 1.8, impactLabel: 'Supports LDL reduction', mechanismNote: 'Concentrated beta-glucan fiber'),
    FoodItem(name: 'Okra', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Supports LDL reduction', mechanismNote: 'Mucilaginous fiber traps cholesterol'),
    FoodItem(name: 'Onions', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Supports heart health', mechanismNote: 'Quercetin reduces LDL oxidation'),
    FoodItem(name: 'Oranges', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Supports LDL reduction', mechanismNote: 'Pectin + hesperidin flavonoid'),
    FoodItem(name: 'Papaya', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Supports heart health', mechanismNote: 'Fiber + antioxidants'),
    FoodItem(name: 'Pears', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Supports LDL reduction', mechanismNote: 'Pectin soluble fiber'),
    FoodItem(name: 'Peas', category: FoodCategory.good, impactScore: 0.7, impactLabel: 'Supports heart health', mechanismNote: 'Soluble fiber + plant protein'),
    FoodItem(name: 'Pomegranate', category: FoodCategory.good, impactScore: 0.8, impactLabel: 'Supports heart health', mechanismNote: 'Punicalagins reduce LDL oxidation'),
    FoodItem(name: 'Pumpkin', category: FoodCategory.good, impactScore: 0.4, impactLabel: 'Heart-healthy vegetable', mechanismNote: 'Beta-carotene + fiber'),
    FoodItem(name: 'Rye', category: FoodCategory.good, impactScore: 1.0, impactLabel: 'Supports LDL reduction', mechanismNote: 'Arabinoxylan soluble fiber'),
    FoodItem(name: 'Soybeans', category: FoodCategory.good, impactScore: 1.2, impactLabel: 'Supports LDL reduction', mechanismNote: 'Soy protein + isoflavones'),
    FoodItem(name: 'Teff', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Whole grain choice', mechanismNote: 'Iron + fiber'),
    FoodItem(name: 'Tempeh', category: FoodCategory.good, impactScore: 1.1, impactLabel: 'Supports LDL reduction', mechanismNote: 'Fermented soy + plant protein'),
    FoodItem(name: 'Tomatoes', category: FoodCategory.good, impactScore: 0.6, impactLabel: 'Supports heart health', mechanismNote: 'Lycopene reduces LDL oxidation'),
    FoodItem(name: 'Whole-Grain Bread', category: FoodCategory.good, impactScore: 0.5, impactLabel: 'Better than white bread', mechanismNote: 'More fiber, lower glycemic index'),
  ];

  static const List<FoodItem> _simpleLimit = [
    FoodItem(name: 'Air-Popped Popcorn', category: FoodCategory.limit, impactScore: -0.1, impactLabel: 'Neutral in small amounts', mechanismNote: 'Whole grain, low fat when plain'),
    FoodItem(name: 'Alcohol (Beer)', category: FoodCategory.limit, impactScore: -0.6, impactLabel: 'Raises triglycerides in excess', mechanismNote: 'Higher carb than wine'),
    FoodItem(name: 'Bagels', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Raises triglycerides', mechanismNote: 'Refined carbs spike blood sugar'),
    FoodItem(name: 'Barbecue Sauce', category: FoodCategory.limit, impactScore: -0.4, impactLabel: 'High sugar raises TG', mechanismNote: 'Added sugars convert to triglycerides'),
    FoodItem(name: 'Cheese (Reduced-Fat)', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Less saturated fat than full-fat', mechanismNote: 'Still contains some saturated fat'),
    FoodItem(name: 'Coconut Milk (Light)', category: FoodCategory.limit, impactScore: -0.6, impactLabel: 'Medium-chain saturated fats', mechanismNote: 'MCTs have debated cholesterol impact'),
    FoodItem(name: 'Coconut Oil', category: FoodCategory.limit, impactScore: -0.9, impactLabel: 'Raises LDL', mechanismNote: '92% saturated fat — use sparingly'),
    FoodItem(name: 'Cream Cheese (Light)', category: FoodCategory.limit, impactScore: -0.4, impactLabel: 'Moderate saturated fat', mechanismNote: 'Better than full-fat version'),
    FoodItem(name: 'Frozen Yogurt', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Sugar raises triglycerides', mechanismNote: 'Less fat but high sugar'),
    FoodItem(name: 'Granola Bars', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Sugar content raises TG', mechanismNote: 'Choose low-sugar varieties'),
    FoodItem(name: 'Honey', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Moderate sugar impact', mechanismNote: 'Fructose contributes to TG'),
    FoodItem(name: 'Ice Cream (Light)', category: FoodCategory.limit, impactScore: -0.6, impactLabel: 'Sugar + some saturated fat', mechanismNote: 'Better than regular; still moderate'),
    FoodItem(name: 'Ketchup', category: FoodCategory.limit, impactScore: -0.2, impactLabel: 'Sugar content adds up', mechanismNote: 'High fructose corn syrup in most brands'),
    FoodItem(name: 'Lamb (Lean Cuts)', category: FoodCategory.limit, impactScore: -0.7, impactLabel: 'Moderate saturated fat', mechanismNote: 'Higher sat fat than chicken; lean cuts only'),
    FoodItem(name: 'Maple Syrup', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Sugar raises triglycerides', mechanismNote: 'Use small amounts'),
    FoodItem(name: 'Mayonnaise (Light)', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Moderate fat content', mechanismNote: 'Better than full-fat mayo'),
    FoodItem(name: 'Milk (1-2% Low-Fat)', category: FoodCategory.limit, impactScore: -0.2, impactLabel: 'Low saturated fat', mechanismNote: 'Acceptable in moderation'),
    FoodItem(name: 'Muffins', category: FoodCategory.limit, impactScore: -0.6, impactLabel: 'Refined carbs + some fat', mechanismNote: 'Spikes blood sugar and TG'),
    FoodItem(name: 'Non-Dairy Creamers', category: FoodCategory.limit, impactScore: -0.4, impactLabel: 'May contain trans fats', mechanismNote: 'Check labels for hydrogenated oils'),
    FoodItem(name: 'Nuts (Small Portions)', category: FoodCategory.limit, impactScore: 0.5, impactLabel: 'Good in moderation', mechanismNote: 'Healthy fats but calorie-dense'),
    FoodItem(name: 'Organ Meats (Rarely)', category: FoodCategory.limit, impactScore: -0.8, impactLabel: 'Very high dietary cholesterol', mechanismNote: 'Liver etc. — only occasionally'),
    FoodItem(name: 'Palm Oil', category: FoodCategory.limit, impactScore: -0.9, impactLabel: 'Raises LDL', mechanismNote: '50% saturated fat'),
    FoodItem(name: 'Pickles', category: FoodCategory.limit, impactScore: -0.1, impactLabel: 'High sodium, not cholesterol', mechanismNote: 'Sodium impacts blood pressure'),
    FoodItem(name: 'Plain Crackers', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Refined carbs raise TG', mechanismNote: 'Choose whole grain versions'),
    FoodItem(name: 'Pork Loin', category: FoodCategory.limit, impactScore: -0.6, impactLabel: 'Moderate saturated fat', mechanismNote: 'Leaner than other pork cuts'),
    FoodItem(name: 'Pork Tenderloin', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Leaner pork cut', mechanismNote: 'Better choice within pork'),
    FoodItem(name: 'Pretzels', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Refined carbs', mechanismNote: 'Low fat but raises blood sugar'),
    FoodItem(name: 'Scallops', category: FoodCategory.limit, impactScore: -0.2, impactLabel: 'Low fat shellfish', mechanismNote: 'Some dietary cholesterol, low sat fat'),
    FoodItem(name: 'Shellfish', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Moderate dietary cholesterol', mechanismNote: 'Generally low in saturated fat'),
    FoodItem(name: 'Lobster', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Moderate dietary cholesterol', mechanismNote: 'Low sat fat but high cholesterol'),
    FoodItem(name: 'Soy Products', category: FoodCategory.limit, impactScore: 0.4, impactLabel: 'Generally beneficial', mechanismNote: 'Isoflavones may support LDL'),
    FoodItem(name: 'Sweetened Nut Milks', category: FoodCategory.limit, impactScore: -0.4, impactLabel: 'Added sugar raises TG', mechanismNote: 'Choose unsweetened versions'),
    FoodItem(name: 'Sweetened Yogurt', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Sugar raises triglycerides', mechanismNote: 'Plain Greek yogurt is far better'),
    FoodItem(name: 'Trail Mix (with Added Sugar)', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Sugar offsets nut benefits', mechanismNote: 'Make your own without candy'),
    FoodItem(name: 'Vegetable Chips (Baked)', category: FoodCategory.limit, impactScore: -0.3, impactLabel: 'Better than fried', mechanismNote: 'Still processed; moderate portions'),
    FoodItem(name: 'White Bread', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Raises triglycerides', mechanismNote: 'Refined carbs spike blood sugar → TG'),
    FoodItem(name: 'White Pasta', category: FoodCategory.limit, impactScore: -0.4, impactLabel: 'Raises triglycerides', mechanismNote: 'Al dente + small portions reduces impact'),
    FoodItem(name: 'White Rice', category: FoodCategory.limit, impactScore: -0.4, impactLabel: 'Raises blood sugar and TG', mechanismNote: 'High glycemic index'),
    FoodItem(name: 'White Rolls', category: FoodCategory.limit, impactScore: -0.5, impactLabel: 'Refined carbs raise TG', mechanismNote: 'Switch to whole grain'),
  ];

  static const List<FoodItem> _simpleAvoid = [
    FoodItem(name: 'Alfredo Sauce', category: FoodCategory.avoid, impactScore: -2.0, impactLabel: 'Very high saturated fat', mechanismNote: 'Heavy cream + butter'),
    FoodItem(name: 'Animal Fats', category: FoodCategory.avoid, impactScore: -2.5, impactLabel: 'Raises LDL significantly', mechanismNote: 'Pure saturated fat'),
    FoodItem(name: 'Bagels (White Flour)', category: FoodCategory.avoid, impactScore: -1.2, impactLabel: 'Refined carbs raise TG', mechanismNote: 'High glycemic, large portions'),
    FoodItem(name: 'Biscuits', category: FoodCategory.avoid, impactScore: -1.5, impactLabel: 'Saturated fat + refined carbs', mechanismNote: 'Butter + white flour combination'),
    FoodItem(name: 'Cakes', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'Saturated fat + sugar', mechanismNote: 'Butter + sugar = double impact'),
    FoodItem(name: 'Candy Bars', category: FoodCategory.avoid, impactScore: -1.6, impactLabel: 'Sugar raises TG', mechanismNote: 'Saturated fat from palm oil too'),
    FoodItem(name: 'Cheddar Cheese', category: FoodCategory.avoid, impactScore: -1.5, impactLabel: 'High saturated fat', mechanismNote: '6g sat fat per 1 oz — adds up fast'),
    FoodItem(name: 'Cheese Balls', category: FoodCategory.avoid, impactScore: -1.5, impactLabel: 'Saturated fat + trans fat', mechanismNote: 'Processed cheese product'),
    FoodItem(name: 'Cheese Puffs', category: FoodCategory.avoid, impactScore: -1.4, impactLabel: 'Saturated fat + refined carbs', mechanismNote: 'Empty calories with fat impact'),
    FoodItem(name: 'Chocolate Milk', category: FoodCategory.avoid, impactScore: -1.3, impactLabel: 'Sugar + saturated fat', mechanismNote: 'High sugar + dairy fat'),
    FoodItem(name: 'Cookies', category: FoodCategory.avoid, impactScore: -1.6, impactLabel: 'Saturated fat + sugar', mechanismNote: 'Butter + refined flour + sugar'),
    FoodItem(name: 'Corned Beef', category: FoodCategory.avoid, impactScore: -2.0, impactLabel: 'High saturated fat', mechanismNote: 'Processed + high fat cut'),
    FoodItem(name: 'Deli Meats', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'Raises LDL + inflammation', mechanismNote: 'Processed meats + sodium nitrates'),
    FoodItem(name: 'Doughnuts', category: FoodCategory.avoid, impactScore: -2.5, impactLabel: 'Trans fat + sugar + sat fat', mechanismNote: 'Fried in shortening + sugar-coated'),
    FoodItem(name: 'Drippings (Meat)', category: FoodCategory.avoid, impactScore: -2.2, impactLabel: 'Concentrated saturated fat', mechanismNote: 'Pure rendered animal fat'),
    FoodItem(name: 'Energy Drinks', category: FoodCategory.avoid, impactScore: -1.6, impactLabel: 'Raises triglycerides', mechanismNote: 'Sugar + stimulants = TG spike'),
    FoodItem(name: 'Flavored Coffee (Sweetened)', category: FoodCategory.avoid, impactScore: -1.2, impactLabel: 'Sugar raises triglycerides', mechanismNote: 'Syrups add 30–50g sugar per drink'),
    FoodItem(name: 'Flavored Tea (Sweetened)', category: FoodCategory.avoid, impactScore: -1.0, impactLabel: 'Sugar raises triglycerides', mechanismNote: 'Bottled teas often high in sugar'),
    FoodItem(name: 'French Fries', category: FoodCategory.avoid, impactScore: -2.8, impactLabel: 'Trans fat + saturated fat', mechanismNote: 'Fried in used oil = trans fats'),
    FoodItem(name: 'Fried Fish (Battered)', category: FoodCategory.avoid, impactScore: -2.2, impactLabel: 'Negates fish benefits', mechanismNote: 'Batter + frying undoes omega-3 benefits'),
    FoodItem(name: 'Full-Fat Cream', category: FoodCategory.avoid, impactScore: -2.3, impactLabel: 'Very high saturated fat', mechanismNote: '~22g sat fat per 100ml'),
    FoodItem(name: 'Full-Fat Milk', category: FoodCategory.avoid, impactScore: -1.3, impactLabel: 'Raises LDL', mechanismNote: 'Switch to 1% or plant-based'),
    FoodItem(name: 'Ghee', category: FoodCategory.avoid, impactScore: -2.4, impactLabel: 'Very high saturated fat', mechanismNote: 'Clarified butter — same impact'),
    FoodItem(name: 'Half and Half', category: FoodCategory.avoid, impactScore: -1.5, impactLabel: 'High saturated fat per serving', mechanismNote: 'Daily coffee creamer adds up'),
    FoodItem(name: 'Ham', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'Processed meat raises LDL', mechanismNote: 'High sodium + saturated fat'),
    FoodItem(name: 'Hot Dogs', category: FoodCategory.avoid, impactScore: -2.2, impactLabel: 'Raises LDL + inflammation', mechanismNote: 'Processed meat + high sat fat'),
    FoodItem(name: 'Instant Noodles', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'Trans fat + refined carbs', mechanismNote: 'Palm oil + white flour = double impact'),
    FoodItem(name: 'Lamb (Fatty Cuts)', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'High saturated fat', mechanismNote: 'Ribs and shoulder are very high'),
    FoodItem(name: 'Lamb Ribs', category: FoodCategory.avoid, impactScore: -2.0, impactLabel: 'Very high saturated fat', mechanismNote: 'One of the fattiest red meat cuts'),
    FoodItem(name: 'Lard', category: FoodCategory.avoid, impactScore: -2.5, impactLabel: 'Very high saturated fat', mechanismNote: 'Pure animal fat'),
    FoodItem(name: 'Margarine', category: FoodCategory.avoid, impactScore: -2.0, impactLabel: 'May contain trans fats', mechanismNote: 'Hydrogenated oils in stick margarine'),
    FoodItem(name: 'Onion Rings (Fried)', category: FoodCategory.avoid, impactScore: -2.0, impactLabel: 'Trans fat from frying', mechanismNote: 'Batter + repeated frying oil'),
    FoodItem(name: 'Palm Kernel Oil', category: FoodCategory.avoid, impactScore: -2.0, impactLabel: 'Raises LDL significantly', mechanismNote: '82% saturated fat'),
    FoodItem(name: 'Pepperoni', category: FoodCategory.avoid, impactScore: -2.3, impactLabel: 'Raises LDL', mechanismNote: 'Processed meat + high sat fat'),
    FoodItem(name: 'Pork Belly', category: FoodCategory.avoid, impactScore: -2.6, impactLabel: 'Very high saturated fat', mechanismNote: 'One of the fattiest pork cuts'),
    FoodItem(name: 'Processed Chips', category: FoodCategory.avoid, impactScore: -1.6, impactLabel: 'Saturated fat + refined carbs', mechanismNote: 'Often fried in saturated oils'),
    FoodItem(name: 'Salami', category: FoodCategory.avoid, impactScore: -2.2, impactLabel: 'Raises LDL', mechanismNote: 'Processed meat + high sat fat'),
    FoodItem(name: 'Smoked Meats', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'Processed + saturated fat', mechanismNote: 'Smoking + processing compound risk'),
    FoodItem(name: 'Soft Drinks', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'Raises triglycerides', mechanismNote: 'High fructose corn syrup → TG'),
    FoodItem(name: 'Spare Ribs', category: FoodCategory.avoid, impactScore: -2.4, impactLabel: 'Very high saturated fat', mechanismNote: 'High fat pork cut + sauce'),
    FoodItem(name: 'Sport Drinks', category: FoodCategory.avoid, impactScore: -1.0, impactLabel: 'Sugar raises triglycerides', mechanismNote: 'Unless actually exercising intensely'),
    FoodItem(name: 'Sugary Cereals', category: FoodCategory.avoid, impactScore: -1.5, impactLabel: 'Raises triglycerides', mechanismNote: 'High sugar spikes insulin → TG'),
    FoodItem(name: 'Sweetened Fruit Drinks', category: FoodCategory.avoid, impactScore: -1.4, impactLabel: 'Fructose raises triglycerides', mechanismNote: 'Not the same as whole fruit'),
    FoodItem(name: 'Whipped Cream', category: FoodCategory.avoid, impactScore: -1.8, impactLabel: 'Very high saturated fat', mechanismNote: '~4g sat fat per 2 tbsp'),
  ];

  // ── Public accessors ───────────────────────────────────────────────────────

  static List<FoodItem> get allFoods =>
      [...featured, ..._simpleGood, ..._simpleLimit, ..._simpleAvoid];

  static List<FoodItem> get goodFoods =>
      allFoods.where((f) => f.category == FoodCategory.good).toList()
        ..sort((a, b) => b.impactScore.compareTo(a.impactScore));

  static List<FoodItem> get limitFoods =>
      allFoods.where((f) => f.category == FoodCategory.limit).toList()
        ..sort((a, b) => b.impactScore.compareTo(a.impactScore));

  static List<FoodItem> get avoidFoods =>
      allFoods.where((f) => f.category == FoodCategory.avoid).toList()
        ..sort((a, b) => a.impactScore.compareTo(b.impactScore));

  /// Best foods for lowering LDL, sorted by impact.
  static List<FoodItem> get topLdlFoods =>
      goodFoods.where((f) => f.helpsLdl).take(4).toList();

  /// Best foods for lowering triglycerides, sorted by impact.
  static List<FoodItem> get topTgFoods =>
      goodFoods.where((f) => f.helpsTriglycerides).take(4).toList();

  /// Top foods for overall heart health (highest overall impact).
  static List<FoodItem> get topOverallFoods => goodFoods.take(4).toList();
}
